#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=exercises'
#      - 'POSTGRES_PASSWORD=password'
#      - 'POSTGRES_USER=postgres'
#    ports:
#      - '5400:5400'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data:

version: '3.8'

services:
  placeholder:
    image: busybox
    command: tail -f /dev/null