services:
  postgres:
    container_name: fitness-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: fitness-backend
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - postgres
    volumes:
      - upload-data:/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fitness-database
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      FILE_UPLOAD_DIR: /uploads  # Configure the upload directory
    restart: always


volumes:
  postgres-data:
  upload-data:
